survey-planet:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host:
    port:
    database:
    username:
    password:

  aliyun:
    # 阿里云OSS配置
    oss:
      endpoint:
      accessKeyId:
      accessKeySecret:
      bucketName:

  # 邮箱配置
  mail:
    host: smtp.163.com
    port: 465
    username: surveyplanet@163.com
    password: # 替换为你生成的密码
    protocol: smtp


  # go-judge 配置
  go-judge:
    baseUrl: http://localhost:5050
    maxProcessNumber: 128
    memoryLimitMb: 512
    stackLimitMb: 128
    stdioSizeMb: 32