survey-planet:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 120.46.3.97
    port: 3306
    database: h_db22373053
    username: u22373053
    password: Aa923051

  aliyun:
    # 阿里云OSS配置
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI5tS6M224UpKHj9vXrL4Z
      accessKeySecret: 9srpqx72xTYdNPpfSN7C3NITN5RAwK
      bucketName: survey-planet-test

  # 邮箱配置
  mail:
    host: smtp.163.com
    port: 465
    username: surveyplanet@163.com
    password: AD6VtDxH3JmDnXu5
    protocol: smtp


  # go-judge 配置
  go-judge:
    baseUrl: http://localhost:5050
    maxProcessNumber: 128
    memoryLimitMb: 512
    stackLimitMb: 128
    stdioSizeMb: 32